server:
  port: 25555
spring:
  application:
    name: provider
dubbo:
  registry:
    address: nacos://127.0.0.1:8848 #注册地址
  application:
    name: provider #应用名
  protocol:
    name: dubbo #dubbo协议
    port: 20880 #协议端口
  scan:
    base-packages: com.liumq.dubbonacos.provider #扫包范围
  provider:
    timeout: 30000 #超时时间
service:
  version: 1.0.0 #自定义的版本
